firstapp/urls.py
from django.urls import path
from . import views

urlpatterns = [

	path("joseph", views.joseph, name="joseph"),
	path("daniel", views.daniel, name="daniel"),

	path("<str:name>", views.greet, name="greet"),
	path("", views.index, name="index"),
	


]

firstpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("firstapp.urls")),
    path('newyear/', include("newyear.urls")),
    path('task/', include("task.urls"))
]

newyear/urls.py
from django.urls import path
from . import views


urlpatterns=[
	path("", views.index, name="index")
]

task/urls.py
from django.urls import path
from . import views

app_name = "task"
urlpatterns = [
	path("", views.index, name="index"),
	path("add/", views.add, name="add"),
]

firstapp/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models

# Create your models here.

firstapp/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def greet(request, name):
	return render(request, "hello/greet.html", {
		"name": name.capitalize()
		})

def index(request):
	return render(request, "hello/index.html")

def joseph(request):
	return HttpResponse("Hello Joseph")

def daniel(request):
	return HttpResponse("Hello Daniel")

newyear/views.py
from django.shortcuts import render
import datetime


def index(request):
	now = datetime.datetime.now()
	return render(request, "newyear/index.html", {
		"newyear": now.month == 1 and now.day == 1
		})
# Create your views here.

task/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect



# Create your views here.
class NewTaskForm(forms.Form):
	task = forms.CharField(label = "New Task")

def index(request):
	if "tasks" not in request.session:
		request.session["tasks"] = []

	return render(request, "task/index.html", {
		"tasks": request.session["tasks"]
		})

def add(request):
	if request.method == "POST":
		form = NewTaskForm(request.POST)
		if form.is_valid():
			task = form.cleaned_data ["task"]
			request.session["tasks"] += [task]
			return HttpResponseRedirect(reverse("task:index"))
		else:
			return render(request, "task/add.html", {
			"form": form
			})

	return render(request, "task/add.html", {
		"form": NewTaskForm()
		})

firstapp/templates/hello/greet.html
<!DOCTYPE html>
<html>
<head>
	<title>Greeting</title>
</head>
<body>
	<h1>Hello {{name}}!!</h1>
</body>
</html>

firstapp/templates/hello/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Hello</title>
</head>
	<h1>Hello Everybody</h1>
	<h3>The names of students in this class</h3>
	<ul>
		<li>Daniel</li>
	</ul>
<body>

</body>
</html>

newyear/templates/newyear/index.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'newyear/styles.css'%}">
	<title>Newyear</title>
</head>
<body>
	{% if newyear %}
		<h1>Yes</h1>
	{% else%}
		<h1>NO</h1>
	{% endif %}
</body>
</html>

task/templates/task/add.html
{% extends "task/layout.html"%}
{% block body %}
	<h1>Add Task:</h1>
	<form action="{% url 'task:add' %}" method="post">
		{% csrf_token %}
		{{form}}
		<input type="submit" name="submit">

	</form>
	<br>
	<a href="{% url 'task:index' %}">View the list</a>
{% endblock %}

task/templates/task/index.html
{% extends "task/layout.html" %}
{% block body %}
	<h3>This is the list</h3>
	<ul>
 	{% for task in tasks %}
 		<li>{{task}}</li>
 	{% endfor %}

 	</ul>
 	<a href="{% url 'task:add' %}"> Add a task</a>

{% endblock %}

task/templates/task/layout.html
<!DOCTYPE html>
<html lang="eng">
<head>
	<title> Add Task</title>
</head>
<body>
	{% block body%}

	{% endblock%}
</body>
</html>